import { LanguageCode } from '../types';

const COPY: Record<LanguageCode, Record<string, string>> = {
  en: {
    executiveCockpit: 'Executive Cockpit', businessAssessment: 'Business Assessment', localOpportunity: 'Local Market Opportunity', feasibility: 'NIRNAY AI Feasibility', finance: 'Financial Structuring & EMI', schemes: 'Scheme & Support Router', growth: '36-Month Growth Projection', report: 'Final Business Plan', dashboard: 'Dashboard',
    selectCity: 'Select Demo City', selectBusiness: 'Select Demo Business', tryDemo: 'Try Demo', demo: 'Demo', activeEvaluation: 'Active Evaluation', in: 'in', resetDemo: 'Reset Demo', askNirnay: 'Ask NIRNAY', voice: 'Voice', viewPlan: 'View Plan', methodology: 'View citations and methodology',
    feasibilityScore: 'Feasibility Score', capitalArchitecture: 'Capital Architecture', statutoryScheme: 'Recommended Scheme', monthlyNetProfit: 'Monthly Net Profit', exploreMetrics: 'Explore SWOT & metrics', viewEmi: 'View EMI & amortization', compareSchemes: 'Compare scheme options', inspectGrowth: 'Inspect 3-year growth curve', fromMargin: 'From margin', loan: 'Loan', afterEmi: 'After EMI', breakEven: 'Break-even in', months: 'months', decisionStatus: 'Decision Status', allQuestionsResolved: 'Core advisory questions resolved', localOpportunityCard: 'Local Opportunity', ideaFeasibility: 'Idea Feasibility', capitalOutlay: 'Capital Outlay', loanStructure: 'Loan Structure', schemeSupport: 'Scheme Support', cityDemoHint: 'Choose a city and business to load a localized demo scenario.', businessDemoHint: 'The demo changes the business plan, capital profile and local market model.'
  },
  hi: {
    executiveCockpit: 'कार्यकारी कॉकपिट', businessAssessment: 'व्यवसाय मूल्यांकन', localOpportunity: 'स्थानीय बाज़ार अवसर', feasibility: 'निर्णय AI व्यवहार्यता', finance: 'वित्तीय संरचना और EMI', schemes: 'योजना एवं सहायता मार्गदर्शक', growth: '36-माह वृद्धि अनुमान', report: 'अंतिम व्यवसाय योजना', dashboard: 'डैशबोर्ड',
    selectCity: 'डेमो शहर चुनें', selectBusiness: 'डेमो व्यवसाय चुनें', tryDemo: 'डेमो चलाएँ', demo: 'डेमो', activeEvaluation: 'सक्रिय मूल्यांकन', in: 'में', resetDemo: 'डेमो रीसेट करें', askNirnay: 'निर्णय से पूछें', voice: 'आवाज़', viewPlan: 'योजना देखें', methodology: 'स्रोत और कार्यप्रणाली देखें',
    feasibilityScore: 'व्यवहार्यता स्कोर', capitalArchitecture: 'पूंजी संरचना', statutoryScheme: 'अनुशंसित योजना', monthlyNetProfit: 'मासिक शुद्ध लाभ', exploreMetrics: 'SWOT और मेट्रिक्स देखें', viewEmi: 'EMI और भुगतान देखें', compareSchemes: 'योजनाओं की तुलना करें', inspectGrowth: '3-वर्ष वृद्धि देखें', fromMargin: 'मार्जिन से', loan: 'ऋण', afterEmi: 'EMI के बाद', breakEven: 'ब्रेक-ईवन', months: 'माह', decisionStatus: 'निर्णय स्थिति', allQuestionsResolved: 'मुख्य सलाह प्रश्न पूरे', localOpportunityCard: 'स्थानीय अवसर', ideaFeasibility: 'विचार व्यवहार्यता', capitalOutlay: 'पूंजी आवश्यकता', loanStructure: 'ऋण संरचना', schemeSupport: 'योजना सहायता', cityDemoHint: 'स्थानीय डेमो के लिए शहर और व्यवसाय चुनें।', businessDemoHint: 'व्यवसाय बदलने पर योजना, पूंजी प्रोफाइल और स्थानीय बाजार मॉडल भी बदलता है।'
  },
  bn: {
    executiveCockpit: 'এক্সিকিউটিভ ককপিট', businessAssessment: 'ব্যবসা মূল্যায়ন', localOpportunity: 'স্থানীয় বাজারের সুযোগ', feasibility: 'NIRNAY AI সম্ভাব্যতা', finance: 'আর্থিক কাঠামো ও EMI', schemes: 'স্কিম ও সহায়তা', growth: '৩৬-মাসের বৃদ্ধি পূর্বাভাস', report: 'চূড়ান্ত ব্যবসা পরিকল্পনা', dashboard: 'ড্যাশবোর্ড',
    selectCity: 'ডেমো শহর বেছে নিন', selectBusiness: 'ডেমো ব্যবসা বেছে নিন', tryDemo: 'ডেমো চালান', demo: 'ডেমো', activeEvaluation: 'সক্রিয় মূল্যায়ন', in: 'এ', resetDemo: 'ডেমো রিসেট', askNirnay: 'NIRNAY-কে জিজ্ঞাসা করুন', voice: 'ভয়েস', viewPlan: 'পরিকল্পনা দেখুন', methodology: 'উৎস ও পদ্ধতি দেখুন',
    feasibilityScore: 'সম্ভাব্যতা স্কোর', capitalArchitecture: 'মূলধন কাঠামো', statutoryScheme: 'প্রস্তাবিত স্কিম', monthlyNetProfit: 'মাসিক নিট লাভ', exploreMetrics: 'SWOT ও মেট্রিক দেখুন', viewEmi: 'EMI দেখুন', compareSchemes: 'স্কিম তুলনা করুন', inspectGrowth: '৩ বছরের বৃদ্ধি দেখুন', fromMargin: 'মার্জিন থেকে', loan: 'ঋণ', afterEmi: 'EMI পরে', breakEven: 'ব্রেক-ইভেন', months: 'মাস', decisionStatus: 'সিদ্ধান্তের অবস্থা', allQuestionsResolved: 'মূল পরামর্শ প্রশ্ন সম্পন্ন', localOpportunityCard: 'স্থানীয় সুযোগ', ideaFeasibility: 'আইডিয়ার সম্ভাব্যতা', capitalOutlay: 'মূলধন ব্যয়', loanStructure: 'ঋণ কাঠামো', schemeSupport: 'স্কিম সহায়তা', cityDemoHint: 'স্থানীয় ডেমোর জন্য শহর ও ব্যবসা বেছে নিন।', businessDemoHint: 'ব্যবসা বদলালে পরিকল্পনা, মূলধন প্রোফাইল ও স্থানীয় বাজার মডেলও বদলায়।'
  },
  mr: {
    executiveCockpit: 'कार्यकारी कॉकपिट', businessAssessment: 'व्यवसाय मूल्यांकन', localOpportunity: 'स्थानिक बाजार संधी', feasibility: 'NIRNAY AI व्यवहार्यता', finance: 'आर्थिक रचना व EMI', schemes: 'योजना व सहाय्य', growth: '36-महिन्यांचा वाढ अंदाज', report: 'अंतिम व्यवसाय योजना', dashboard: 'डॅशबोर्ड',
    selectCity: 'डेमो शहर निवडा', selectBusiness: 'डेमो व्यवसाय निवडा', tryDemo: 'डेमो चालवा', demo: 'डेमो', activeEvaluation: 'सक्रिय मूल्यांकन', in: 'मध्ये', resetDemo: 'डेमो रीसेट', askNirnay: 'NIRNAY ला विचारा', voice: 'आवाज', viewPlan: 'योजना पहा', methodology: 'स्रोत व पद्धत पहा',
    feasibilityScore: 'व्यवहार्यता गुण', capitalArchitecture: 'भांडवल रचना', statutoryScheme: 'शिफारस केलेली योजना', monthlyNetProfit: 'मासिक निव्वळ नफा', exploreMetrics: 'SWOT व मेट्रिक्स पहा', viewEmi: 'EMI पहा', compareSchemes: 'योजना तुलना', inspectGrowth: '3-वर्ष वाढ पहा', fromMargin: 'मार्जिनमधून', loan: 'कर्ज', afterEmi: 'EMI नंतर', breakEven: 'ब्रेक-ईव्हन', months: 'महिने', decisionStatus: 'निर्णय स्थिती', allQuestionsResolved: 'मुख्य सल्ला प्रश्न पूर्ण', localOpportunityCard: 'स्थानिक संधी', ideaFeasibility: 'कल्पना व्यवहार्यता', capitalOutlay: 'भांडवली खर्च', loanStructure: 'कर्ज रचना', schemeSupport: 'योजना सहाय्य', cityDemoHint: 'स्थानिक डेमोसाठी शहर आणि व्यवसाय निवडा.', businessDemoHint: 'व्यवसाय बदलल्यावर योजना, भांडवल प्रोफाइल आणि स्थानिक बाजार मॉडेल बदलते.'
  },
  ta: {
    executiveCockpit: 'நிர்வாக கட்டுப்பாட்டு மையம்', businessAssessment: 'வணிக மதிப்பீடு', localOpportunity: 'உள்ளூர் சந்தை வாய்ப்பு', feasibility: 'NIRNAY AI சாத்தியக்கூறு', finance: 'நிதி அமைப்பு & EMI', schemes: 'திட்டம் மற்றும் ஆதரவு', growth: '36 மாத வளர்ச்சி கணிப்பு', report: 'இறுதி வணிகத் திட்டம்', dashboard: 'டாஷ்போர்டு',
    selectCity: 'டெமோ நகரை தேர்ந்தெடுக்கவும்', selectBusiness: 'டெமோ வணிகத்தை தேர்ந்தெடுக்கவும்', tryDemo: 'டெமோ இயக்கவும்', demo: 'டெமோ', activeEvaluation: 'செயலில் உள்ள மதிப்பீடு', in: 'இல்', resetDemo: 'டெமோ மீட்டமை', askNirnay: 'NIRNAY-யிடம் கேளுங்கள்', voice: 'குரல்', viewPlan: 'திட்டம் பார்க்க', methodology: 'ஆதாரங்கள் மற்றும் முறை பார்க்க',
    feasibilityScore: 'சாத்தியக்கூறு மதிப்பெண்', capitalArchitecture: 'மூலதன அமைப்பு', statutoryScheme: 'பரிந்துரைக்கப்பட்ட திட்டம்', monthlyNetProfit: 'மாத நிகர லாபம்', exploreMetrics: 'SWOT மற்றும் அளவுகள்', viewEmi: 'EMI பார்க்க', compareSchemes: 'திட்டங்கள் ஒப்பிட', inspectGrowth: '3 ஆண்டு வளர்ச்சி', fromMargin: 'மார்ஜினிலிருந்து', loan: 'கடன்', afterEmi: 'EMIக்கு பின்', breakEven: 'பிரேக்-ஈவன்', months: 'மாதங்கள்', decisionStatus: 'முடிவு நிலை', allQuestionsResolved: 'முக்கிய ஆலோசனை கேள்விகள் முடிந்தது', localOpportunityCard: 'உள்ளூர் வாய்ப்பு', ideaFeasibility: 'யோசனை சாத்தியக்கூறு', capitalOutlay: 'மூலதன செலவு', loanStructure: 'கடன் அமைப்பு', schemeSupport: 'திட்ட ஆதரவு', cityDemoHint: 'உள்ளூர் டெமோவிற்கு நகரமும் வணிகமும் தேர்ந்தெடுக்கவும்.', businessDemoHint: 'வணிகத்தை மாற்றினால் திட்டம், மூலதன சுயவிவரம் மற்றும் உள்ளூர் சந்தை மாதிரி மாறும்.'
  },
  te: {
    executiveCockpit: 'ఎగ్జిక్యూటివ్ కాక్‌పిట్', businessAssessment: 'వ్యాపార అంచనా', localOpportunity: 'స్థానిక మార్కెట్ అవకాశం', feasibility: 'NIRNAY AI సాధ్యత', finance: 'ఆర్థిక నిర్మాణం & EMI', schemes: 'పథకం & సహాయం', growth: '36 నెలల వృద్ధి అంచనా', report: 'చివరి వ్యాపార ప్రణాళిక', dashboard: 'డ్యాష్‌బోర్డ్',
    selectCity: 'డెమో నగరం ఎంచుకోండి', selectBusiness: 'డెమో వ్యాపారం ఎంచుకోండి', tryDemo: 'డెమో నడపండి', demo: 'డెమో', activeEvaluation: 'సక్రియ అంచనా', in: 'లో', resetDemo: 'డెమో రీసెట్', askNirnay: 'NIRNAYని అడగండి', voice: 'వాయిస్', viewPlan: 'ప్రణాళిక చూడండి', methodology: 'మూలాలు మరియు విధానం చూడండి',
    feasibilityScore: 'సాధ్యత స్కోర్', capitalArchitecture: 'మూలధన నిర్మాణం', statutoryScheme: 'సిఫార్సు చేసిన పథకం', monthlyNetProfit: 'నెలవారీ నికర లాభం', exploreMetrics: 'SWOT & మెట్రిక్స్', viewEmi: 'EMI చూడండి', compareSchemes: 'పథకాలు పోల్చండి', inspectGrowth: '3 ఏళ్ల వృద్ధి', fromMargin: 'మార్జిన్ నుంచి', loan: 'రుణం', afterEmi: 'EMI తరువాత', breakEven: 'బ్రేక్-ఈవెన్', months: 'నెలలు', decisionStatus: 'నిర్ణయ స్థితి', allQuestionsResolved: 'ప్రధాన సలహా ప్రశ్నలు పూర్తయ్యాయి', localOpportunityCard: 'స్థానిక అవకాశం', ideaFeasibility: 'ఆలోచన సాధ్యత', capitalOutlay: 'మూలధన వ్యయం', loanStructure: 'రుణ నిర్మాణం', schemeSupport: 'పథకం సహాయం', cityDemoHint: 'స్థానిక డెమో కోసం నగరం మరియు వ్యాపారం ఎంచుకోండి.', businessDemoHint: 'వ్యాపారం మారితే ప్రణాళిక, మూలధన ప్రొఫైల్ మరియు స్థానిక మార్కెట్ మోడల్ మారుతుంది.'
  },
  kn: {
    executiveCockpit: 'ಕಾರ್ಯನಿರ್ವಾಹಕ ಕಾಕ್‌ಪಿಟ್', businessAssessment: 'ವ್ಯವಹಾರ ಮೌಲ್ಯಮಾಪನ', localOpportunity: 'ಸ್ಥಳೀಯ ಮಾರುಕಟ್ಟೆ ಅವಕಾಶ', feasibility: 'NIRNAY AI ಸಾಧ್ಯತೆ', finance: 'ಹಣಕಾಸು ರಚನೆ & EMI', schemes: 'ಯೋಜನೆ ಮತ್ತು ಬೆಂಬಲ', growth: '36 ತಿಂಗಳ ಬೆಳವಣಿಗೆ ಅಂದಾಜು', report: 'ಅಂತಿಮ ವ್ಯವಹಾರ ಯೋಜನೆ', dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    selectCity: 'ಡೆಮೊ ನಗರ ಆಯ್ಕೆಮಾಡಿ', selectBusiness: 'ಡೆಮೊ ವ್ಯವಹಾರ ಆಯ್ಕೆಮಾಡಿ', tryDemo: 'ಡೆಮೊ ಚಾಲನೆ', demo: 'ಡೆಮೊ', activeEvaluation: 'ಸಕ್ರಿಯ ಮೌಲ್ಯಮಾಪನ', in: 'ನಲ್ಲಿ', resetDemo: 'ಡೆಮೊ ಮರುಹೊಂದಿಸಿ', askNirnay: 'NIRNAY ಅನ್ನು ಕೇಳಿ', voice: 'ಧ್ವನಿ', viewPlan: 'ಯೋಜನೆ ನೋಡಿ', methodology: 'ಮೂಲಗಳು ಮತ್ತು ವಿಧಾನ ನೋಡಿ',
    feasibilityScore: 'ಸಾಧ್ಯತಾ ಅಂಕ', capitalArchitecture: 'ಬಂಡವಾಳ ರಚನೆ', statutoryScheme: 'ಶಿಫಾರಸು ಯೋಜನೆ', monthlyNetProfit: 'ಮಾಸಿಕ ಶುದ್ಧ ಲಾಭ', exploreMetrics: 'SWOT ಮತ್ತು ಅಳತೆಗಳು', viewEmi: 'EMI ನೋಡಿ', compareSchemes: 'ಯೋಜನೆ ಹೋಲಿಕೆ', inspectGrowth: '3 ವರ್ಷದ ಬೆಳವಣಿಗೆ', fromMargin: 'ಮಾರ್ಜಿನ್‌ನಿಂದ', loan: 'ಸಾಲ', afterEmi: 'EMI ನಂತರ', breakEven: 'ಬ್ರೇಕ್-ಈವನ್', months: 'ತಿಂಗಳು', decisionStatus: 'ನಿರ್ಧಾರ ಸ್ಥಿತಿ', allQuestionsResolved: 'ಮುಖ್ಯ ಸಲಹೆ ಪ್ರಶ್ನೆಗಳು ಪೂರ್ಣ', localOpportunityCard: 'ಸ್ಥಳೀಯ ಅವಕಾಶ', ideaFeasibility: 'ಕಲ್ಪನೆ ಸಾಧ್ಯತೆ', capitalOutlay: 'ಬಂಡವಾಳ ವೆಚ್ಚ', loanStructure: 'ಸಾಲ ರಚನೆ', schemeSupport: 'ಯೋಜನೆ ಬೆಂಬಲ', cityDemoHint: 'ಸ್ಥಳೀಯ ಡೆಮೊಗಾಗಿ ನಗರ ಮತ್ತು ವ್ಯವಹಾರ ಆಯ್ಕೆಮಾಡಿ.', businessDemoHint: 'ವ್ಯವಹಾರ ಬದಲಾಗಿದರೆ ಯೋಜನೆ, ಬಂಡವಾಳ ಪ್ರೊಫೈಲ್ ಮತ್ತು ಸ್ಥಳೀಯ ಮಾರುಕಟ್ಟೆ ಮಾದರಿ ಬದಲಾಗುತ್ತದೆ.'
  },
  gu: {
    executiveCockpit: 'એક્ઝિક્યુટિવ કોકપિટ', businessAssessment: 'વ્યવસાય મૂલ્યાંકન', localOpportunity: 'સ્થાનિક બજાર તક', feasibility: 'NIRNAY AI શક્યતા', finance: 'નાણાકીય માળખું & EMI', schemes: 'યોજના અને સહાય', growth: '36-મહિના વૃદ્ધિ અનુમાન', report: 'અંતિમ વ્યવસાય યોજના', dashboard: 'ડેશબોર્ડ',
    selectCity: 'ડેમો શહેર પસંદ કરો', selectBusiness: 'ડેમો બિઝનેસ પસંદ કરો', tryDemo: 'ડેમો ચલાવો', demo: 'ડેમો', activeEvaluation: 'સક્રિય મૂલ્યાંકન', in: 'માં', resetDemo: 'ડેમો રીસેટ', askNirnay: 'NIRNAY ને પૂછો', voice: 'વૉઇસ', viewPlan: 'યોજના જુઓ', methodology: 'સ્ત્રોત અને પદ્ધતિ જુઓ',
    feasibilityScore: 'શક્યતા સ્કોર', capitalArchitecture: 'મૂડી માળખું', statutoryScheme: 'ભલામણ કરેલી યોજના', monthlyNetProfit: 'માસિક નેટ નફો', exploreMetrics: 'SWOT અને મેટ્રિક્સ', viewEmi: 'EMI જુઓ', compareSchemes: 'યોજનાઓ સરખાવો', inspectGrowth: '3 વર્ષ વૃદ્ધિ', fromMargin: 'માર્જિનથી', loan: 'લોન', afterEmi: 'EMI પછી', breakEven: 'બ્રેક-ઈવન', months: 'મહિના', decisionStatus: 'નિર્ણય સ્થિતિ', allQuestionsResolved: 'મુખ્ય સલાહ પ્રશ્નો પૂર્ણ', localOpportunityCard: 'સ્થાનિક તક', ideaFeasibility: 'વિચાર શક્યતા', capitalOutlay: 'મૂડી ખર્ચ', loanStructure: 'લોન માળખું', schemeSupport: 'યોજના સહાય', cityDemoHint: 'સ્થાનિક ડેમો માટે શહેર અને બિઝનેસ પસંદ કરો.', businessDemoHint: 'બિઝનેસ બદલતાં પ્લાન, મૂડી પ્રોફાઇલ અને સ્થાનિક બજાર મોડેલ બદલાય છે.'
  },
  pa: {
    executiveCockpit: 'ਐਗਜ਼ਿਕਿਊਟਿਵ ਕਾਕਪਿਟ', businessAssessment: 'ਕਾਰੋਬਾਰ ਮੁਲਾਂਕਣ', localOpportunity: 'ਸਥਾਨਕ ਬਾਜ਼ਾਰ ਮੌਕਾ', feasibility: 'NIRNAY AI ਸੰਭਾਵਨਾ', finance: 'ਵਿੱਤੀ ਢਾਂਚਾ ਅਤੇ EMI', schemes: 'ਯੋਜਨਾ ਅਤੇ ਸਹਾਇਤਾ', growth: '36-ਮਹੀਨੇ ਵਾਧਾ ਅਨੁਮਾਨ', report: 'ਅੰਤਿਮ ਕਾਰੋਬਾਰੀ ਯੋਜਨਾ', dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    selectCity: 'ਡੈਮੋ ਸ਼ਹਿਰ ਚੁਣੋ', selectBusiness: 'ਡੈਮੋ ਕਾਰੋਬਾਰ ਚੁਣੋ', tryDemo: 'ਡੈਮੋ ਚਲਾਓ', demo: 'ਡੈਮੋ', activeEvaluation: 'ਸਕ੍ਰਿਆ ਮੁਲਾਂਕਣ', in: 'ਵਿੱਚ', resetDemo: 'ਡੈਮੋ ਰੀਸੈਟ', askNirnay: 'NIRNAY ਨੂੰ ਪੁੱਛੋ', voice: 'ਆਵਾਜ਼', viewPlan: 'ਯੋਜਨਾ ਵੇਖੋ', methodology: 'ਸਰੋਤ ਅਤੇ ਵਿਧੀ ਵੇਖੋ',
    feasibilityScore: 'ਸੰਭਾਵਨਾ ਸਕੋਰ', capitalArchitecture: 'ਪੂੰਜੀ ਢਾਂਚਾ', statutoryScheme: 'ਸਿਫਾਰਸ਼ੀ ਯੋਜਨਾ', monthlyNetProfit: 'ਮਾਸਿਕ ਨਿੱਟ ਲਾਭ', exploreMetrics: 'SWOT ਅਤੇ ਮੈਟ੍ਰਿਕਸ', viewEmi: 'EMI ਵੇਖੋ', compareSchemes: 'ਯੋਜਨਾਵਾਂ ਦੀ ਤੁਲਨਾ', inspectGrowth: '3 ਸਾਲ ਵਾਧਾ', fromMargin: 'ਮਾਰਜਿਨ ਤੋਂ', loan: 'ਕਰਜ਼ਾ', afterEmi: 'EMI ਤੋਂ ਬਾਅਦ', breakEven: 'ਬ੍ਰੇਕ-ਈਵਨ', months: 'ਮਹੀਨੇ', decisionStatus: 'ਫੈਸਲਾ ਸਥਿਤੀ', allQuestionsResolved: 'ਮੁੱਖ ਸਲਾਹ ਸਵਾਲ ਪੂਰੇ', localOpportunityCard: 'ਸਥਾਨਕ ਮੌਕਾ', ideaFeasibility: 'ਵਿਚਾਰ ਸੰਭਾਵਨਾ', capitalOutlay: 'ਪੂੰਜੀ ਖਰਚ', loanStructure: 'ਕਰਜ਼ਾ ਢਾਂਚਾ', schemeSupport: 'ਯੋਜਨਾ ਸਹਾਇਤਾ', cityDemoHint: 'ਸਥਾਨਕ ਡੈਮੋ ਲਈ ਸ਼ਹਿਰ ਅਤੇ ਕਾਰੋਬਾਰ ਚੁਣੋ।', businessDemoHint: 'ਕਾਰੋਬਾਰ ਬਦਲਣ ਨਾਲ ਯੋਜਨਾ, ਪੂੰਜੀ ਪ੍ਰੋਫਾਈਲ ਅਤੇ ਸਥਾਨਕ ਬਾਜ਼ਾਰ ਮਾਡਲ ਬਦਲਦਾ ਹੈ।'
  },
};

export function demoT(key: string, language: LanguageCode): string {
  return COPY[language]?.[key] || COPY.en[key] || key;
}
