import {
  AssessmentFormData,
  LocalOpportunityData,
  FeasibilityScoreData,
  SWOTData,
  MapMarkerItem,
} from '../types';

/**
 * Legacy neutral fallback data. Current demos are generated by demoScenarios.ts.
 * Keep these exports generic so an AI/network fallback never leaks dairy-specific
 * claims into Tailoring, IT, Poultry, Repair or other businesses.
 */
export const DEMO_SCENARIO: AssessmentFormData = {
  location: {
    village: 'Selected locality',
    block: 'Selected block',
    district: 'Selected district',
    state: 'Uttar Pradesh',
  },
  marginCapital: 50000,
  availableMargin: 50000,
  category: 'Other',
  ideaText: 'Local micro-enterprise selected by the entrepreneur.',
  businessIdea: 'Local Micro-Enterprise',
  targetMarket: 'Nearby households, shops and institutional customers to be validated locally',
  priorExperience: 'Some',
  riskWillingness: 'Medium',
  preferredLanguage: 'en',
};

export const DEMO_ASSESSMENT_DATA = DEMO_SCENARIO;

export const DEMO_MAP_MARKERS: MapMarkerItem[] = [];

export const DEMO_LOCAL_OPPORTUNITY: LocalOpportunityData = {
  locationSummary: 'Selected locality and district',
  radiusKm: 10,
  localDemand: 'Requires local validation',
  demandSignal: 'A plausible local demand route may exist, but customer interviews and test sales are required before investment.',
  marketGap: 'Potential gaps may include reliability, quality, convenience, pricing or organized delivery; verify these locally.',
  competition: 'Use the live market map and field checks to identify both mapped and informal competitors.',
  competitorDensity: 'Not assumed in fallback mode; inspect the live map and verify locally.',
  recommendedRadius: 'Start with a 3–8 km test cluster and expand after repeat demand is demonstrated.',
  suggestedProductMix: [
    'Core high-frequency offer',
    'Value-added secondary offer',
    'Bulk or institutional package',
  ],
  customerSegments: [
    'Nearby households',
    'Local shops and service businesses',
    'Institutions or bulk buyers relevant to the selected category',
  ],
  dataConfidence: 'Medium',
  sources: [
    'NIRNAY AI entrepreneur profile',
    'Live market map when available',
    'Local verification checklist',
  ],
  markers: [],
  evidenceBadge: 'VERIFY_LOCALLY',
};

export const DEMO_FEASIBILITY_SCORE: FeasibilityScoreData = {
  overallScore: 75,
  statusLabel: 'Promising — validate locally and scale in stages',
  marketPotential: 77,
  capitalFit: 75,
  competitionScore: 70,
  operationalFeasibility: 76,
  growthPotential: 77,
};

export const DEMO_SWOT: SWOTData = {
  strengths: [
    'The entrepreneur can begin with a controlled pilot aligned to available resources.',
    'Local customer feedback can be collected before committing the full project cost.',
  ],
  weaknesses: [
    'Demand, pricing and supplier reliability still require field validation.',
  ],
  opportunities: [
    'A focused local route can reveal repeat customers and category-specific gaps.',
  ],
  threats: [
    'Competition, input-price changes and execution delays can reduce projected returns.',
  ],
};

export const DEMO_AI_INSIGHTS = [
  {
    title: 'Validate demand before fixed-cost spending',
    description: 'Speak to likely customers, test pricing and secure early orders before buying the full equipment or inventory package.',
    tag: 'Validation',
  },
  {
    title: 'Protect working capital',
    description: 'Keep a cash reserve for slow sales, repairs, replenishment and customer-credit delays.',
    tag: 'Cash Flow',
  },
  {
    title: 'Verify official finance and scheme terms',
    description: 'Treat financing outputs as planning estimates and confirm current eligibility, rates, documents and sanction terms with the official portal and lender.',
    tag: 'Finance Safety',
  },
];
